### ISSUE TITLE
Why  G-domain sequences

### ISSUE THREAD

**Issue by ahy1221** [acrinklaw/HLAQuant#1]
Hi 
It is exciting to see such a tool explicit to do allele-specific expression for HLA allele.
I am also working on HLA allele specific expression. In my own pipeline , I use kallisto to quantify the whole CDS sequence from IMGT.
I was wondering that why do you use only G-domain sequences ? 
Yao He

**Comment by acrinklaw** [comment]
Hi Yao,

That is great! It has been very fun to see all these researchers interested lately in new ways of measuring HLA expression, it seems the past few months many groups have been publishing and many have faced the same questions we have as far as requiring such a tool.

I apologize for the delay in reply, and I would like to provide you empirical evidence of why we perform quantification with G-domain sequences but am unable to do so now in the format of a Github comment, but keep an eye out for when we submit our results for publication. I will link our preprint when it is uploaded - we are currently very busy overhauling our pipeline and doing analysis on some datasets, as well as comparing our results to [HLApers](https://github.com/genevol-usp/HLApers), which I assume you are aware of.

I will say that using G-domain sequences is for a very specific case example, and that for most intents and purposes using the full length CDS should provide high quality results - as shown in the HLApers manuscript.

I was a little too excited to make our tool public after having inquiries at a recent conference about testing and availability. Hope you understand and thanks for your interest.

Austin
